ROBOT_KEY_STORES = {
    ##### base group ###
    "ret_code": "ret_code",
    "create_on": "create_on",
    "err_msg": "err_msg",
    ########## robot info group #######
    "id": "id",
    "vehicle_id": "vehicle_id",
    "robot_note": "robot_note",
    "version": "version",
    "model": "model",
    "dsp_version": "dsp_version",
    "gyro_version": "gyro_version",
    "map_version": "map_version",
    "model_version": "model_version",
    "netprotocol_version": "netprotocol_version",
    "modbus_version": "modbus_version",
    "current_map": "current_map",
    "current_map_md5": "current_map_md5",
    "model_md5": "model_md5",
    "ssid": "ssid",
    "rssi": "rssi",
    "ap_addr": "ap_addr",
    "current_ip": "current_ip",
    "MAC": "MAC",
    "echoid_type": "echoid_type",
    "echoid": "echoid",
    "features": "features",
    ##################### robot block group ################
    "blocked": "blocked",
    "block_reason": "block_reason",
    "virtual": "virtual",
    "block_x": "block_x",
    "block_y": "block_y",
    "block_ultrasonic_id": "block_ultrasonic_id",
    "block_di": "block_di",
    "block_id": "block_id",
    "slow_reason": "slow_reason",
    "slow_x": "slow_x",
    "slow_y": "slow_y",
    "slow_ultrasonic_id": "slow_ultrasonic_id",
    "slow_di": "slow_di",
    ##################### robot baterry group ################
    "battery_level": "battery_level",
    "battery_temp": "battery_temp",
    "battery_cycle": "battery_cycle",
    "battery_user_data": "battery_user_data",
    "charging": "charging",
    "voltage": "voltage",
    "current": "current",
    "max_charge_voltage": "max_charge_voltage",
    "max_charge_current": "max_charge_current",
    "manual_charge": "manual_charge",
    "auto_charge": "auto_charge",
    ##################### location group ################
    "x": "x",
    "y": "y",
    "angle": "angle",
    "confidence": "confidence",
    "current_station": "current_station",
    "last_station": "last_station",
    ######### navigation group ##########
    "task_status": "task_status",
    "task_type": "task_type",
    "target_id": "target_id",
    "target_point": "target_point",
    "finished_path": "finished_path",
    "unfinished_path": "unfinished_path",
    "move_status_info": "move_status_info",
    "containers": "containers",
    ######### running group ##########
    "odo": "odo",
    "today_odo": "today_odo",
    "time": "time",
    "total_time": "total_time",
    "controller_temp": "controller_temp",
    "controller_humi": "controller_humi",
    "controller_voltage": "controller_voltage",
    ######### speed group ######
    "vx": "vx",
    "vy": "vy",
    "w": "w",
    "steer": "steer",
    "spin": "spin",
    "r_vx": "r_vx",
    "r_vy": "r_vy",
    "r_w": "r_w",
    "r_steer": "r_steer",
    "r_spin": "r_spin",
    "steer_angles": "steer_angles",
    "r_steer_angles": "r_steer_angles",
    "is_stop": "is_stop",
    ######### task status #########
    "closest_target": "closest_target",
    "source_name": "source_name",
    "target_name": "target_name",
    "percentage": "percentage",
    "distance": "distance",
    "task_status_list": "task_status_list",
    "info": "info",
    ########## jack group #########
    "jack_mode": "jack_mode",
    "jack_state": "jack_state",
    "jack_enable": "jack_enable",
    "jack_error_code": "jack_error_code",
    "jack_isFull": "jack_isFull",
    "jack_speed": "jack_speed",
    "jack_emc": "jack_emc",
    "jack_height": "jack_height",
    "peripheral_data": "peripheral_data",
    ####### roller ########
    "roller_mode": "roller_mode",
    "roller_state": "roller_state",
    "roller_enable": "roller_enable",
    "roller_error_code": "roller_error_code",
    "roller_isFull": "roller_isFull",
    "roller_speed": "roller_speed",
    "roller_emc": "roller_emc",
    "peripheral_data": "peripheral_data",
    ########## fork #######
    "fork_height": "fork_height",
    "fork_height_in_place": "fork_height_in_place",
    "fork_auto_flag": "fork_auto_flag",
    "forward_val": "forward_val",
    "forward_in_place": "forward_in_place",
    "fork_pressure_actual": "fork_pressure_actual",
    ######## emergency #######
    "emergency": "emergency",
    "driver_emc": "driver_emc",
    "electric": "electric",
    "soft_emc": "soft_emc",
    ########### lock_info #########
    "locked": "locked",
    "ip": "ip",
    "port": "port",
    "nick_name": "nick_name",
    "time_t": "time_t",
    "desc": "desc",
    ########### alarm #########
    "errors": "errors",
    "warnings": "warnings",
    "notices": "notices",
    "fatals": "fatals",
    ############ single #####
    "area_ids": "area_ids",
    "stations": "stations",
    "sound_name": "sound_name",
    "loadmap_status": "loadmap_status",
    "reloc_status": "reloc_status",
    "slam_status": "slam_status",
    ### DI, DO ######
    "DI": "DI",
    "DO": "DO",
}

STATUS_FRAME = {"keys": [], "return_laser": False, "return_beams3D": False}


def get_frame_keys(keys):
    status_keys = [x for x in keys if x in ROBOT_KEY_STORES]
    frame_key = {**STATUS_FRAME}
    frame_key["keys"] = status_keys
    return frame_key
